environments:
  # Staging Listesi
  staging-list:
    servers:
      - id: "staging-1"
      - id: "staging-2"
      - id: "staging-3"
      - id: "staging-4"
      - id: "Exe-1"
      - id: "Exe-2"
      - id: "Heyy-1"
      - id: "Heyy-2"

  # Prod Listesi
  prod-list:
    servers:
      - id: "prod-1"
      - id: "prod-2"
      - id: "batch-1"
