name: Deploy to Staging Servers

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        server: ["staging-1", "staging-2", "staging-3", "staging-4"]

    steps:
      - name: Print Server Name
        run: echo "Deploying to ${{ matrix.server }}"
