name: Staging Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: >
          Deployment Environment.
          'all' → tüm staging deploy'ları çalışır,
          'staging-1', 'staging-2' gibi spesifik değerler.
        required: true
        default: "all"
        type: string
      action:
        description: "What action would you like to perform?"
        required: true
        default: "deploy"
        type: choice
        options:
          - deploy
          - rollback

jobs:
  deploy-staging:
    name: "Deploy Staging"
    runs-on: ubuntu-latest
    env:
      ALL_STAGING_SERVERS: '["staging-1", "staging-2", "staging-3", "staging-4"]'

    strategy:
      max-parallel: 1
      matrix:
        environment: ${{ inputs.environment == 'all' && fromJson('["staging-1", "staging-2", "staging-3", "staging-4"]') || fromJson(format('["{0}"]', inputs.environment)) }}

    steps:
      - name: Print Matrix Environment
        run: echo "Deploying to ${{ matrix.environment }}"
