name: Deploy Jobs

on:
  workflow_call:
    inputs:
      environments:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        environment: ${{ fromJson(inputs.environments) }}
    steps:
      - name: Checkout Deploy Repository
        uses: actions/checkout@v4
        with:
          clean: true

      - name: Simulated Deploy - ${{ matrix.environment }}
        run: |
          case "${{ matrix.environment }}" in
            "staging-1") echo "Deploying: 1" ;;
            "staging-2") echo "Deploying: 2" ;;
            "staging-3") echo "Deploying: 3" ;;
            "staging-4") echo "Deploying: 4" ;;
            *) echo "Unknown environment" ;;
          esac
