name: Test For Skip Job

on:
  workflow_dispatch:
    inputs:
      RUN_BATCH0:
        description: "Batch0 çalıştırılsın mı?"
        required: true
        type: boolean
        default: true
      RUN_BATCH1:
        description: "Batch1 çalıştırılsın mı?"
        required: true
        type: boolean
        default: true
      RUN_STATIC:
        description: "Static çalıştırılsın mı?"
        required: true
        type: boolean
        default: true
      DEPLOY_TYPE:
        description: "Static için deploy tipi seçin: 'full' = Tam deploy, 'only-css-js' = Sadece css + js"
        required: true
        default: "full"
        type: choice
        options:
          - "full"
          - "only-css-js"
      RUN_BATCH2:
        description: "Batch2 çalıştırılsın mı?"
        required: true
        type: boolean
        default: true
      RUN_PROD1:
        description: "Prod1 çalıştırılsın mı?"
        required: true
        type: boolean
        default: true
      RUN_PROD2:
        description: "Prod2 çalıştırılsın mı?"
        required: true
        type: boolean
        default: true
      RUN_PROD3:
        description: "Prod3 çalıştırılsın mı?"
        required: true
        type: boolean
        default: true

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Git Pull
        run: echo "Deploy job çalıştı"

  Batch0:
    if: ${{ always() }}
    needs: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Batch0
        if: ${{ github.event.inputs.RUN_BATCH0 == 'true' }}
        run: echo "Batch0 job çalıştı"

  Batch1:
    if: ${{ always() }}
    needs: Batch0
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Batch1
        if: ${{ github.event.inputs.RUN_BATCH1 == 'true' }}
        run: echo "Batch1 job çalıştı"

  Static:
    if: ${{ always() }}
    needs: Batch1
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Static - Full
        if: ${{ github.event.inputs.DEPLOY_TYPE == 'full' && github.event.inputs.RUN_STATIC == 'true' }}
        run: echo "Static Full job çalıştı"

      - name: Deploy Static - Only CSS & JS
        if: ${{ github.event.inputs.DEPLOY_TYPE == 'only-css-js' && github.event.inputs.RUN_STATIC == 'true' }}
        run: echo "Static Only CSS & JS job çalıştı"

  Batch2:
    if: ${{ always() }}
    needs: Static
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Batch2
        if: ${{ github.event.inputs.RUN_BATCH2 == 'true' }}
        run: echo "Batch2 job çalıştı"

  Prod1:
    if: ${{ always() }}
    needs: Batch2
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Prod1
        if: ${{ github.event.inputs.RUN_PROD1 == 'true' }}
        run: echo "Prod1 job çalıştı"

  Prod2:
    if: ${{ always() }}
    needs: Prod1
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Prod2
        if: ${{ github.event.inputs.RUN_PROD2 == 'true' }}
        run: echo "Prod2 job çalıştı"

  Prod3:
    if: ${{ always() }}
    needs: Prod2
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Prod3
        if: ${{ github.event.inputs.RUN_PROD3 == 'true' }}
        run: echo "Prod3 job çalıştı"
