name: Staging Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: >
          Deployment Environment.
          'all' → tüm staging deploy'ları çalışır,
          'staging-1', 'staging-2' gibi spesifik değerler.
        required: true
        default: "all"
        type: string
      action:
        description: "What action would you like to perform?"
        required: true
        default: "deploy"
        type: choice
        options:
          - deploy
          - rollback

jobs:
  deploy-staging:
    name: "Deploy Staging Environments"
    runs-on: self-hosted
    steps:
      - name: Staging Servers'ı Yükle
        run: echo "STAGING_SERVERS=$(grep 'staging_servers' liste/staging_servers.yml | cut -d ' ' -f2-)" >> $GITHUB_ENV

      - name: Tanımlı Staging Sunucularını Ayarla
        id: define_matrix
        run: |
          if [ "${{ inputs.environment }}" == "all" ]; then
            echo "matrix_env=${{ env.STAGING_SERVERS }}" >> $GITHUB_ENV
          else
            echo "matrix_env=[\"${{ inputs.environment }}\"]" >> $GITHUB_ENV
          fi

  deploy-instances:
    needs: deploy-staging
    runs-on: self-hosted
    strategy:
      max-parallel: 1
      matrix:
        environment: ${{ fromJson(env.matrix_env) }}
    steps:
      - name: Test Deploy - ${{ matrix.environment }}
        run: echo "Test Mode:"
