name: Deploy to Staging

on:
  workflow_dispatch:
    inputs:
      environment:
        description: >
          Staging Environment.
          'all' → Tüm staging sunucuları,
          veya 'staging-1', 'staging-2', ... gibi belirli bir sunucu.
        required: true
        default: "all"
        type: string
      action:
        description: "Gerçekleştirilecek işlem?"
        required: true
        default: "deploy"
        type: choice
        options:
          - deploy
          - rollback
          - first-setup

jobs:
  call-base:
    uses: ./.github/workflows/base-staging-cicd.yaml
    with:
      environment: ${{ github.event.inputs.environment }}
      action: ${{ github.event.inputs.action }}
      STAGING_SERVERS: '["staging-5", "staging-6", "staging-7", "staging-8"]'
