name: CI/CD Multi-Pipeline

on:
  workflow_dispatch:  # Manuel tetikleme ile başlatılacak

jobs:
  # Staging Pipeline
  staging-indirme:
    name: Staging - Kod Indirme
    runs-on: ubuntu-latest
    steps:
      - name: Kod indirme
        run: echo "İndirme yapılıyor"
        
  staging-yukleme:
    name: Staging - Yukleme
    runs-on: ubuntu-latest
    needs: staging-indirme
    steps:
      - name: Yükleme
        run: echo "Staging ortamına yükleme yapılıyor"

  staging-test:
    name: Staging - Test
    runs-on: ubuntu-latest
    needs: staging-yukleme
    steps:
      - name: Test
        run: echo "Staging testleri yapılıyor"



  # Batch Pipeline
  batch-indirme:
    name: Batch - Kod Indirme
    runs-on: ubuntu-latest
    needs: [staging-yukleme, staging-test, staging-indirme]
    steps:
      - name: Kod indirme
        run: echo "İndirme yapılıyor"

  batch-yukleme:
    name: Batch - Yukleme
    runs-on: ubuntu-latest
    needs: batch-indirme
    steps:
      - name: Yükleme
        run: echo "Batch ortamına yükleme yapılıyor"

  batch-test:
    name: Batch - Test
    runs-on: ubuntu-latest
    needs: batch-yukleme
    steps:
      - name: Test
        run: echo "Batch testleri yapılıyor"



  # Prod Pipeline
  prod-indirme:
    name: Prod - Kod Indirme
    runs-on: ubuntu-latest
    needs: [batch-indirme, batch-test]
    steps:
      - name: Kod indirme
        run: echo "İndirme yapılıyor"

  prod-yukleme:
    name: Prod - Yukleme
    runs-on: ubuntu-latest
    needs: prod-indirme
    steps:
      - name: Yükleme
        run: echo "Prod ortamına yükleme yapılıyor"

  prod-test:
    name: Prod - Test
    runs-on: ubuntu-latest
    needs: prod-yukleme
    steps:
      - name: Test
        run: echo "Prod testleri yapılıyor"
