name: CI/CD Multi-Pipeline

on:
  workflow_dispatch:  # Manuel tetikleme ile başlatılacak

jobs:
  # Staging Pipeline
  staging:
    name: Staging Pipeline
    runs-on: ubuntu-latest
    steps:
      - name: Kod indirme
        uses: actions/checkout@v3

      - name: Staging - Yükleme
        run: echo "Staging ortamına yükleme yapılıyor"

      - name: Staging - Test
        run: echo "Staging testleri yapılıyor"

  # Batch Pipeline (Staging tamamlandıktan sonra başlar)
  batch:
    name: Batch Pipeline
    runs-on: ubuntu-latest
    needs: staging  # Staging tamamlanmadan başlamaz
    steps:
      - name: Kod indirme
        uses: actions/checkout@v3

      - name: Batch - Yükleme
        run: echo "Batch ortamına yükleme yapılıyor"

      - name: Batch - Test
        run: echo "Batch testleri yapılıyor"

  # Prod Pipeline (Batch tamamlandıktan sonra başlar)
  prod:
    name: Prod Pipeline
    runs-on: ubuntu-latest
    needs: batch  # Batch tamamlanmadan başlamaz
    steps:
      - name: Kod indirme
        uses: actions/checkout@v3

      - name: Prod - Yükleme
        run: echo "Prod ortamına yükleme yapılıyor"

      - name: Prod - Test
        run: echo "Prod testleri yapılıyor"
