name: Staging Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: >
          Deployment Environment.
          'all' → tüm staging deploy'ları çalışır,
          'staging-1', 'staging-2' gibi spesifik değerler.
        required: true
        default: "all"
        type: string
      action:
        description: "What action would you like to perform?"
        required: true
        default: "deploy"
        type: choice
        options:
          - deploy
          - rollback

jobs:
  set-matrix:
    runs-on: ubuntu-latest
    outputs:
      environments: ${{ steps.set-matrix.outputs.environments }}
    environment: example  # Burada GitHub Environments kullanıyoruz!
    steps:
      - name: Set matrix dynamically from GitHub Environments
        id: set-matrix
        run: |
          echo "Available environment variable list:"
          printenv  # Debug amaçlı ortam değişkenlerini yazdır.

          if [[ "${{ inputs.environment }}" == "all" ]]; then
            # GitHub Environments içinde tanımlı değişkeni JSON formatında oku
            echo "environments=${{ vars.staging_example_1 }}" >> $GITHUB_OUTPUT
          else
            echo "environments=$(echo '["${{ inputs.environment }}"]' | jq -c)" >> $GITHUB_OUTPUT
          fi

  call-jobs:
    needs: set-matrix
    uses: ./.github/workflows/jobs.yml
    with:
      environments: ${{ needs.set-matrix.outputs.environments }}
