name: Staging Deployment

on: [push]

jobs:
  deploy-staging:
    name: "Deploy Staging Environments"
    runs-on: windows-latest
    env:
      STAGING_SERVERS: '["staging-1", "staging-2", "staging-3", "staging-4"]'
    outputs:
      matrix_env: ${{ steps.define_matrix.outputs.matrix_env }}
    steps:
      - name: Tanımlı Staging Sunucularını Ayarla
        id: define_matrix
        shell: pwsh
        run: |
          if ("${{ github.event.inputs.environment }}" -eq "all") {
            "matrix_env=${{ env.STAGING_SERVERS }}" | Tee-Object -FilePath $env:GITHUB_OUTPUT
          } else {
            "matrix_env=[`"${{ github.event.inputs.environment }}`"]" | Tee-Object -FilePath $env:GITHUB_OUTPUT
          }

      - name: Debug Çıktıyı Gör
        run: echo "Matrix Env ${{ steps.define_matrix.outputs.matrix_env }}"

  deploy-instances:
    needs: deploy-staging
    runs-on: windows-latest
    strategy:
      max-parallel: 1  # Paralel çalışmayı önler, işlemleri sırayla çalıştırır.
      matrix:
        environment: ${{ fromJson(needs.deploy-staging.outputs.matrix_env) }}
    steps:
      - name: Test Deploy - ${{ matrix.environment }}
        shell: pwsh
        run: |
          Write-Output "Test Mode - Deploying to $($env:MATRIX_ENVIRONMENT) with action ${{ github.event.inputs.action }}"
