name: Staging Deploy 2

on:
  workflow_dispatch:
    inputs:
      environment:
        description: >
          Deployment Environment.
          'all' → tüm staging deploy'ları çalışır,
          'staging-1', 'staging-2' gibi spesifik değerler.
        required: true
        default: "all"
        type: string
      action:
        description: "What action would you like to perform?"
        required: true
        default: "deploy"
        type: choice
        options:
          - deploy
          - rollback

jobs:
  deploy-staging:
    name: "Deploy Staging Environments"
    runs-on: windows-latest
    env:
      STAGING_SERVERS: '["staging-1", "staging-2", "staging-3", "staging-4"]'
    outputs:
      matrix_env: ${{ steps.define_matrix.outputs.matrix_env }}
    steps:
      - name: Tanımlı Staging Sunucularını Ayarla
        id: define_matrix
        run: |
          if ($env:GITHUB_EVENT.inputs.environment -eq "all") {
            Write-Output "matrix_env=$env:STAGING_SERVERS" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append
          } else {
            Write-Output "matrix_env=[`"$($env:GITHUB_EVENT.inputs.environment)`"]" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append
          }
        shell: pwsh
  
  deploy-instances:
    needs: deploy-staging
    runs-on: windows-latest
    strategy:
      max-parallel: 1  # Paralel çalışmayı önler, işlemleri sırayla çalıştırır.
      matrix:
        environment: ${{ fromJson(needs.deploy-staging.outputs.matrix_env) }}
    steps:
      - name: Test Deploy - ${{ matrix.environment }}
        run: Write-Output "Test Mode - Deploying to ${{ matrix.environment }} with action ${{ github.event.inputs.action }}"
        shell: pwsh
