name: CI/CD Multi-Pipeline

on:
  workflow_dispatch:  # Manuel tetikleme ile başlatılacak

jobs:
  # Staging Pipeline
  staging-indirme:
    name: Staging - Kod Indirme
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
    steps:
      - name: Kod indirme
        uses: actions/checkout@v3

  staging-yukleme:
    name: Staging - Yukleme
    runs-on: ubuntu-latest
    needs: staging-indirme
    strategy:
      max-parallel: 1
    steps:
      - name: Yükleme
        run: echo "Staging ortamına yükleme yapılıyor"

  staging-test:
    name: Staging - Test
    runs-on: ubuntu-latest
    needs: staging-yukleme
    strategy:
      max-parallel: 1
    steps:
      - name: Test
        run: echo "Staging testleri yapılıyor"

  # Batch Pipeline
  batch-indirme:
    name: Batch - Kod Indirme
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
    steps:
      - name: Kod indirme
        uses: actions/checkout@v3

  batch-yukleme:
    name: Batch - Yukleme
    runs-on: ubuntu-latest
    needs: batch-indirme
    strategy:
      max-parallel: 1
    steps:
      - name: Yükleme
        run: echo "Batch ortamına yükleme yapılıyor"

  batch-test:
    name: Batch - Test
    runs-on: ubuntu-latest
    needs: batch-yukleme
    strategy:
      max-parallel: 1
    steps:
      - name: Test
        run: echo "Batch testleri yapılıyor"

  # Prod Pipeline
  prod-indirme:
    name: Prod - Kod Indirme
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
    steps:
      - name: Kod indirme
        uses: actions/checkout@v3

  prod-yukleme:
    name: Prod - Yukleme
    runs-on: ubuntu-latest
    needs: prod-indirme
    strategy:
      max-parallel: 1
    steps:
      - name: Yükleme
        run: echo "Prod ortamına yükleme yapılıyor"

  prod-test:
    name: Prod - Test
    runs-on: ubuntu-latest
    needs: prod-yukleme
    strategy:
      max-parallel: 1
    steps:
      - name: Test
        run: echo "Prod testleri yapılıyor"
