name: Read Staging Servers

on:
  workflow_dispatch:

jobs:
  print_servers:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Read and Print Staging Servers
        shell: pwsh
        run: |
          $content = Get-Content liste/staging-servers.yml
          $match = ($content -match '^staging_servers:\s*''\[(.*)\]''$') -replace 'staging_servers:\s*''\[','' -replace '\]''$',''
          $servers = $match -split '",\s*"'
          foreach ($server in $servers) {
              Write-Output "Staging Server: $server"
          }
